host: http://ccp.noc.net.cn
userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
accounts:
- phone: 13388888888
  password: CcpNoc
version: v1.0.0
